### PR TITLE
Improve bounding box calculations

### PR DESCRIPTION
**Pull request by OzGav**
Simplify bounding box calculation

# Proposed Changes

As per the request here https://github.com/home-assistant/core/issues/45453 a simplified approach to calculating the bounding box.

## Related Issues

Nil

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by joostlek** [comment]
Okay so the tests seem to fail since the values are different than the old one. I am very much not an expert on coordinates and kilometers, so if there's a website we can take as truth I'd happily use them as guideline.

One thing I did notice while debugging the test (0.0, 0.0, 25 kilometer radius), min longitude is a positive number, and max longitude is also positive. I would expect the min longitude to be negative here.

**Comment by OzGav** [comment]
Sorry I have been too busy to look into this. Will try and find some time tomorrow.

**Comment by OzGav** [comment]
60 nautical miles equates to 1deg of latitude change
I used this site https://www.programiz.com/python-programming/online-compiler/ and plugged in the code

Using latitude=0 longitude=0 and radius=111120 (60nm in metres) I got:
-0.9993261684968934
-0.9993261684968934
0.9993261684968934
0.9993261684968934

So that is close enough to 1 for me. So what actual values did you get when you tested it?

**Comment by OzGav** [comment]
The only issue I can obviously see if when the longitude is within 180+/-0.99999 degrees the longitude split is between 0-2 degrees instead of 2. Since no one lives there we could just accept that to have a close enough approximation. I will continue to look at other algorithms to see if there is a simple enough option that works better.

**Comment by OzGav** [comment]
I found another (slightly more complex) algorithm and for all intents and purposes it produces the same results but is better around that 180 longitude mark. So I think what we have is practically fine for everyone's use. Let me know what you think. I don't know why you are seeing min longitude as positive?

**Comment by joostlek** [comment]
I don't really have an opinion on what method we should use, I think for the purpose of HA we should at least know what the deviation would be in meters (as people fill it in in meters). And we should be able to properly test it, we can create a lot of testcases to proof this so the automated tests can pick them up.

**Comment by OzGav** [comment]
Well for now I think use what we have but we need to work out why you are seeing a positive min longitude in your test as I don’t in my test

**Comment by joostlek** [comment]
Are you known with unit tests and pytest? If you pull the changes I made you can run pytest

**Comment by OzGav** [comment]
It seems to me the test is failing but I suggest the tolerance is too small or the value being compared is incorrect. You can see above the two algorithms give 0.2248 then a slight divergence in values not 0.2261 as per the test

**Comment by joostlek** [comment]
> It seems to me the test is failing but I suggest the tolerance is too small or the value being compared is incorrect. You can see above the two algorithms give 0.2248 then a slight divergence in values not 0.2261 as per the test

I just now modified the test to use parametrize so we can add more testcases easily.

Is there a way we can make a baseline? As in what you had with the nautical miles. So we would say, starting point x,y we move z kilometers to north, this is the exact answer. That would be our testcase. Then we would need to define our max deviation. So if we say, the function we use can have a deviation up to A degrees

**Comment by joostlek** [comment]
So the test is now testing if starting from (0.0, 0.0) and we have a radius of 111.120 meters, we should get the values min_lat=-1, max_lat=+1, min_lon=-1, max_lon=+1. And we check for a deviation of 0.001.
But then we get back to the problem I had previously, for some reason the min_lat is the same as the max_lat, which is incorrect imo

**Comment by OzGav** [comment]
Maybe I would have to think about it. The planet is not a perfect sphere so the 60nm = 1 degree is not entirely precise and while it generally holds in latitude it does not in longitude because the longitude lines converge at the poles. 
Is it permissible to just say the code is using an accepted algorithm?

**Comment by joostlek** [comment]
In the current code, the latitude is a bit fucked haha, if I fill in (90.0,0.0) the bounding box is (89.0, 89.0, -90.0, 90.0) and it should be something along the lines of (89.0, 91.0, -1.0, 1.0)

**Comment by OzGav** [comment]
Yeah most simple algorithms will fail if you put in one of the poles as the centre. But I would point out that the longitude will be no where near only 1 degree at that latitude due to the convergence.

**Comment by joostlek** [comment]
> Yeah most simple algorithms will fail if you put in one of the poles as the centre. But I would point out that the longitude will be no where near only 1 degree at that latitude due to the convergence.

Right. Also excuse me if you're starting to repeat some stuff, but I think I am getting what you mean haha. Is there some website or place where we can find the precise values we can use as approximate goals which also takes the convergence in account? 

For now I think we need to check if we can make these tests work (or at least get in the direction of the expected values) since now the expected values are no where near the ones we actually get from this function

**Comment by OzGav** [comment]
Correct. I don't know if we can find a set of truth values. You will probably only find algorithms and thus it will be a self fullfilling prophecy to check that this code generates the same value as the same code used elsewhere :-!

**Comment by OzGav** [comment]
Just changed to the better algorithm which doesn't fail at 180 longitude. How to test it though... I am running it in that python interpreter and saying "that looks reasonable". Perhaps that is enough to pytest confirm this code is producing the same values that we have looked and said appear reasonable?

**Comment by joostlek** [comment]
Ah, the way you created the bounding box was incorrect. Fixed that now

**Comment by OzGav** [comment]
Well that has me perplexed as my fork doesn't have that error? Anyway well spotted. So that should work ok now for all but very close to the pole. This will be good enough for the purposes of opensky I suggest.

**Comment by joostlek** [comment]
Hmm, for some reason linting only fires after reopening, need to look into that

**Comment by OzGav** [comment]
Do you want me to fix those linting issues or will you do it? Line too long...really...

**Comment by joostlek** [comment]
> Do you want me to fix those linting issues or will you do it? Line too long...really...

I copied the whole project setup from Frencks projects, and I really like it. If you install the pre-commit hooks, they fix everything for you. But I am first adding the linter to PRs, then I push my commit with the fixed (`black .\src\python_opensky\opensky.py`)

**Comment by joostlek** [comment]
https://github.com/home-assistant/core/pull/93916

**Pull request merged**
